namespace RotationSolver.Tests;

internal static partial class PvPTestSuite
{
	internal static IReadOnlyList<TestCase> Tests { get; } =
	[
		new("after-combat cancel is cleared by territory change", AfterCombatCancelIsClearedByTerritoryChange),
		new("after-combat cancel does not fire after combat restarts", AfterCombatCancelDoesNotFireAfterCombatRestarts),
		new("after-combat cancel fires only after expiry in same context", AfterCombatCancelFiresOnlyAfterExpiryInSameContext),
		new("countdown-owned state continues into combat", CountdownOwnedStateContinuesIntoCombat),
		new("countdown cleanup does not cancel user-owned state", CountdownCleanupDoesNotCancelUserOwnedState),
		new("countdown cleanup cancels owned state without combat", CountdownCleanupCancelsOwnedStateWithoutCombat),
		new("disabled countdown clears ownership", DisabledCountdownClearsOwnership),
		new("pvp smart default preset is ranked", PvPSmartDefaultPresetIsRanked),
		new("pvp smart default weights match ranked", PvPSmartDefaultWeightsMatchRanked),
		new("legacy custom pvp weights fill new control defaults", LegacyCustomPvPWeightsFillNewControlDefaults),
		new("legacy casual pvp weights are detected", LegacyCasualPvPWeightsAreDetected),
		new("legacy default pvp weights migrate to ranked defaults", LegacyDefaultPvPWeightsMigrateToRankedDefaults),
		new("legacy pvp scoring config migrates default preset and weights", LegacyPvPScoringConfigMigratesDefaultPresetAndWeights),
		new("pvp combatant queries find hostile by id", PvPCombatantQueriesFindHostileById),
		new("pvp combatant queries count ally focus", PvPCombatantQueriesCountAllyFocus),
		new("pvp combatant queries count hostiles targeting ally", PvPCombatantQueriesCountHostilesTargetingAlly),
		new("pvp combatant queries count nearby hostiles", PvPCombatantQueriesCountNearbyHostiles),
		new("pvp combatant queries count nearby allies", PvPCombatantQueriesCountNearbyAllies),
		new("pvp combatant queries measure nearest hostile distance", PvPCombatantQueriesMeasureNearestHostileDistance),
		new("pvp combatant queries count hostiles in line", PvPCombatantQueriesCountHostilesInLine),
		new("pvp combatant queries line count rejects zero length direction", PvPCombatantQueriesLineCountRejectsZeroLengthDirection),
		new("pvp combatant queries line count rejects hostiles beyond range", PvPCombatantQueriesLineCountRejectsHostilesBeyondRange),
		new("pvp combatant queries line count includes hitbox boundary", PvPCombatantQueriesLineCountIncludesHitboxBoundary),
		new("pvp single target action use restricts target and maps options", PvPSingleTargetActionUseRestrictsTargetAndMapsOptions),
		new("pvp single target action use restores predicate after failure", PvPSingleTargetActionUseRestoresPredicateAfterFailure),
		new("pvp single target action use composes original predicate", PvPSingleTargetActionUseComposesOriginalPredicate),
		new("pvp single target action use rejects zero target without predicate change", PvPSingleTargetActionUseRejectsZeroTargetWithoutPredicateChange),
		new("mp pressure scores low and medium mp", MpPressureScoresLowAndMediumMp),
		new("pvp scoring health pressure scales missing health by weight", PvPScoringHealthPressureScalesMissingHealthByWeight),
		new("objective pressure scores known objective target", ObjectivePressureScoresKnownObjectiveTarget),
		new("resilience penalty scores boolean signal", ResiliencePenaltyScoresBooleanSignal),
		new("silent nocturne rejects filler use", SilentNocturneRejectsFillerUse),
		new("silent nocturne rejects resilient target", SilentNocturneRejectsResilientTarget),
		new("silent nocturne accepts casting shutdown", SilentNocturneAcceptsCastingShutdown),
		new("silent nocturne rejects guarded target", SilentNocturneRejectsGuardedTarget),
		new("silent nocturne secures kill through recuperate", SilentNocturneSecuresKillThroughRecuperate),
		new("silent nocturne rejects secure when burst kills regardless", SilentNocturneRejectsSecureWhenBurstKillsRegardless),
		new("silent nocturne rejects secure when burst cannot kill", SilentNocturneRejectsSecureWhenBurstCannotKill),
		new("silent nocturne rejects secure when target cannot recuperate", SilentNocturneRejectsSecureWhenTargetCannotRecuperate),
		new("silent nocturne rejects secure when effective hp degenerate", SilentNocturneRejectsSecureWhenEffectiveHpDegenerate),
		new("silent nocturne rejects secure when target invulnerable", SilentNocturneRejectsSecureWhenTargetInvulnerable),
		new("silent nocturne fires on engaged target", SilentNocturneFiresOnEngagedTarget),
		new("repelling rejects unsafe backstep", RepellingRejectsUnsafeBackstep),
		new("repelling rejects resilient target", RepellingRejectsResilientTarget),
		new("repelling accepts safe peel", RepellingAcceptsSafePeel),
		new("bard forced burst rejects blocked target", BardForcedBurstRejectsBlockedTarget),
		new("bard burst gate cannot override blocked target", BardBurstGateCannotOverrideBlockedTarget),
		new("bard forced burst allows unblocked target", BardForcedBurstAllowsUnblockedTarget),
		new("bard apex arrow rejects active blast arrow window", BardApexArrowRejectsActiveBlastArrowWindow),
		new("bard apex arrow allows missing blast arrow window", BardApexArrowAllowsMissingBlastArrowWindow),
		new("protective paean rejects healthy unfocused ally", ProtectivePaeanRejectsHealthyUnfocusedAlly),
		new("protective paean allows focused ally", ProtectivePaeanAllowsFocusedAlly),
		new("machinist target policy prefers killable low resource target", MachinistTargetPolicyPrefersKillableLowResourceTarget),
		new("machinist target policy prefers direct secure target", MachinistTargetPolicyPrefersDirectSecureTarget),
		new("machinist target policy prefers team focused non lb target", MachinistTargetPolicyPrefersTeamFocusedNonLbTarget),
		new("machinist target policy keeps direct secure above team focus", MachinistTargetPolicyKeepsDirectSecureAboveTeamFocus),
		new("machinist target policy derives ally focus from count", MachinistTargetPolicyDerivesAllyFocusFromCount),
		new("machinist target policy does not boost marksman team focus", MachinistTargetPolicyDoesNotBoostMarksmanTeamFocus),
		new("machinist target policy does not boost eagle eye team focus", MachinistTargetPolicyDoesNotBoostEagleEyeTeamFocus),
		new("machinist target policy allows guarded drill punish", MachinistTargetPolicyAllowsGuardedDrillPunish),
		new("machinist analysis drill rejects full resource target", MachinistAnalysisDrillRejectsFullResourceTarget),
		new("machinist analysis drill accepts direct secure kill", MachinistAnalysisDrillAcceptsDirectSecureKill),
		new("machinist analysis air anchor rejects resilient target", MachinistAnalysisAirAnchorRejectsResilientTarget),
		new("machinist analysis air anchor accepts direct secure through resilience", MachinistAnalysisAirAnchorAcceptsDirectSecureThroughResilience),
		new("machinist analysis air anchor rejects isolated setup", MachinistAnalysisAirAnchorRejectsIsolatedSetup),
		new("machinist analysis chain saw requires follow up", MachinistAnalysisChainSawRequiresFollowUp),
		new("machinist scattergun rejects unsafe close range", MachinistScattergunRejectsUnsafeCloseRange),
		new("machinist wildfire requires committed target and follow up", MachinistWildfireRequiresCommittedTargetAndFollowUp),
		new("machinist bishop accepts objective teamfight", MachinistBishopAcceptsObjectiveTeamfight),
		new("machinist bishop rejects out of range targets", MachinistBishopRejectsOutOfRangeTargets),
		new("machinist target policy breaks score ties by health then id", MachinistTargetPolicyBreaksScoreTiesByHealthThenId),
		new("machinist marksmans spite rejects guard", MachinistMarksmanSpiteRejectsGuard),
		new("machinist marksmans spite holds on dying ally focused target", MachinistMarksmanSpiteHoldsOnDyingAllyFocusedTarget),
		new("machinist marksmans spite accepts secure damage", MachinistMarksmanSpiteAcceptsSecureDamage),
		new("machinist marksmans spite rejects guard ready solo execute target", MachinistMarksmanSpiteRejectsGuardReadySoloExecuteTarget),
		new("machinist marksmans spite rejects unknown guard solo execute target", MachinistMarksmanSpiteRejectsUnknownGuardSoloExecuteTarget),
		new("machinist marksmans spite rejects low mp nonlethal target", MachinistMarksmanSpiteRejectsLowMpNonlethalTarget),
		new("machinist marksmans spite accepts ally backed nonlethal target", MachinistMarksmanSpiteAcceptsAllyBackedNonlethalTarget),
		new("machinist marksmans spite accepts focused allied burst nonlethal target", MachinistMarksmanSpiteAcceptsFocusedAlliedBurstNonlethalTarget),
		new("machinist marksmans spite accepts objective backed nonlethal target", MachinistMarksmanSpiteAcceptsObjectiveBackedNonlethalTarget),
		new("machinist marksmans spite rejects objective pressure without focus", MachinistMarksmanSpiteRejectsObjectivePressureWithoutFocus),
		new("machinist marksmans spite rejects unfocused ally proximity", MachinistMarksmanSpiteRejectsUnfocusedAllyProximity),
		new("machinist marksmans spite rejects unsupported narrow lethal target", MachinistMarksmanSpiteRejectsUnsupportedNarrowLethalTarget),
		new("machinist marksmans spite rejects objective conversion above leftover cap", MachinistMarksmanSpiteRejectsObjectiveConversionAboveLeftoverCap),
		new("machinist marksmans spite rejects focused ally conversion above leftover cap", MachinistMarksmanSpiteRejectsFocusedAllyConversionAboveLeftoverCap),
		new("machinist marksmans spite rejects focused pressure above tight cap", MachinistMarksmanSpiteRejectsFocusedPressureAboveTightCap),
		new("machinist marksmans spite accepts vulnerable target", MachinistMarksmanSpiteAcceptsVulnerableTarget),
		new("machinist marksmans spite rejects vulnerable pressure target", MachinistMarksmanSpiteRejectsVulnerablePressureTarget),
		new("machinist marksmans spite rejects unsupported vulnerable target", MachinistMarksmanSpiteRejectsUnsupportedVulnerableTarget),
		new("machinist marksmans spite rejects active invulnerability", MachinistMarksmanSpiteRejectsActiveInvulnerability),
		new("machinist marksmans spite accepts mitigated secure kill", MachinistMarksmanSpiteAcceptsMitigatedSecureKill),
		new("machinist marksmans spite rejects conversion without guard cooldown knowledge", MachinistMarksmanSpiteRejectsConversionWithoutGuardCooldownKnowledge),
		new("machinist marksmans spite rejects guard ready conversion target", MachinistMarksmanSpiteRejectsGuardReadyConversionTarget),
		new("machinist marksmans spite rejects unknown guard conversion target", MachinistMarksmanSpiteRejectsUnknownGuardConversionTarget),
		new("machinist marksmans spite accepts guard cooldown conversion target", MachinistMarksmanSpiteAcceptsGuardCooldownConversionTarget),
		new("machinist marksmans spite rejects focused finisher in strict mode", MachinistMarksmanSpiteRejectsFocusedFinisherInStrictMode),
		new("machinist marksmans spite accepts strict execute on guard cooldown", MachinistMarksmanSpiteAcceptsStrictExecuteOnGuardCooldown),
		new("machinist marksmans spite rejects strict cc unknown guard", MachinistMarksmanSpiteRejectsStrictCcUnknownGuard),
		new("machinist marksmans spite rejects strict unknown guard recuperate survivor", MachinistMarksmanSpiteRejectsStrictUnknownGuardRecuperateSurvivor),
		new("machinist marksmans spite uses caller recuperate ratio", MachinistMarksmanSpiteUsesCallerRecuperateRatio),
		new("machinist marksmans spite accepts strict unknown guard very low health", MachinistMarksmanSpiteAcceptsStrictUnknownGuardVeryLowHealth),
		new("machinist marksmans spite accepts strict unknown guard very low mp", MachinistMarksmanSpiteAcceptsStrictUnknownGuardVeryLowMp),
		new("machinist marksmans spite rejects strict unknown guard without low signal", MachinistMarksmanSpiteRejectsStrictUnknownGuardWithoutLowSignal),
		new("machinist marksmans spite rejects strict unknown guard mitigated recuperate survivor", MachinistMarksmanSpiteRejectsStrictUnknownGuardMitigatedRecuperateSurvivor),
		new("machinist marksmans spite rejects strict unknown guard mitigated low health survivor", MachinistMarksmanSpiteRejectsStrictUnknownGuardMitigatedLowHealthSurvivor),
		new("machinist marksmans spite preserves non strict unknown guard execute", MachinistMarksmanSpitePreservesNonStrictUnknownGuardExecute),
		new("machinist marksmans spite rejects unknown guard lethal emergency", MachinistMarksmanSpiteRejectsUnknownGuardLethalEmergency),
		new("machinist marksmans spite identity rejects adjusted drill", MachinistMarksmanSpiteIdentityRejectsAdjustedDrill),
		new("machinist marksmans spite live guard veto blocks inherited pierce", MachinistMarksmanSpiteLiveGuardVetoBlocksInheritedPierce),
		new("machinist analysis chain saw accepts low resource kill window", MachinistAnalysisChainSawAcceptsLowResourceKillWindow),
		new("machinist full metal rejects uncommitted follow up", MachinistFullMetalRejectsUncommittedFollowUp),
		new("machinist full metal accepts direct secure without follow up", MachinistFullMetalAcceptsDirectSecureWithoutFollowUp),
		new("machinist full metal rejects guarded direct secure", MachinistFullMetalRejectsGuardedDirectSecure),
		new("machinist full metal rejects out of range direct secure", MachinistFullMetalRejectsOutOfRangeDirectSecure),
		new("machinist blazing shot accepts direct secure without follow up", MachinistBlazingShotAcceptsDirectSecureWithoutFollowUp),
		new("pvp damage gate rejects invulnerability", PvpDamageGateRejectsInvulnerability),
		new("pvp damage gate allows mitigated secure kill", PvpDamageGateAllowsMitigatedSecureKill),
		new("pvp final guard gate blocks stale guarded target", PvpFinalGuardGateBlocksStaleGuardedTarget),
		new("pvp final guard gate allows guard piercing action", PvpFinalGuardGateAllowsGuardPiercingAction),
		new("pvp final guard gate allows expiring guard", PvpFinalGuardGateAllowsExpiringGuard),
		new("pvp final guard gate allows nonhostile action", PvpFinalGuardGateAllowsNonhostileAction),
		new("pvp guard cooldown tracker backdates observed guard", PvpGuardCooldownTrackerBackdatesObservedGuard),
		new("pvp guard cooldown tracker keeps cooldown after early cancel", PvpGuardCooldownTrackerKeepsCooldownAfterEarlyCancel),
		new("pvp guard cooldown tracker requires safe unavailable window", PvpGuardCooldownTrackerRequiresSafeUnavailableWindow),
		new("pvp guard cooldown tracker forgets stale unseen targets", PvpGuardCooldownTrackerForgetsStaleUnseenTargets),
		new("pvp guard cooldown tracker forgets target", PvpGuardCooldownTrackerForgetsTarget),
		new("bard forced burst allows direct secure target", BardForcedBurstAllowsDirectSecureTarget),
		new("bard forced burst rejects blocked direct secure target", BardForcedBurstRejectsBlockedDirectSecureTarget),
		new("bard kill secure ranks lethal hostile", BardKillSecureRanksLethalHostile),
		new("bard kill secure rejects invulnerability", BardKillSecureRejectsInvulnerability),
		new("bard kill secure prefers lowest lethal health", BardKillSecurePrefersLowestLethalHealth),
		new("bard offensive target policy prefers direct secure target", BardOffensiveTargetPolicyPrefersDirectSecureTarget),
		new("bard offensive target policy prefers low mp target", BardOffensiveTargetPolicyPrefersLowMpTarget),
		new("bard offensive target policy prefers team focused non lb target", BardOffensiveTargetPolicyPrefersTeamFocusedNonLbTarget),
		new("bard offensive target policy keeps direct secure above team focus", BardOffensiveTargetPolicyKeepsDirectSecureAboveTeamFocus),
		new("bard offensive target policy derives ally focus from count", BardOffensiveTargetPolicyDerivesAllyFocusFromCount),
		new("bard offensive target policy does not boost eagle eye team focus", BardOffensiveTargetPolicyDoesNotBoostEagleEyeTeamFocus),
		new("bard offensive target policy uses pitch perfect splash value", BardOffensiveTargetPolicyUsesPitchPerfectSplashValue),
		new("bard offensive target policy rejects out of range target", BardOffensiveTargetPolicyRejectsOutOfRangeTarget),
		new("bard offensive target policy keeps eagle eye guard target", BardOffensiveTargetPolicyKeepsEagleEyeGuardTarget),
		new("bard offensive target policy treats guarded eagle eye target as exposed", BardOffensiveTargetPolicyTreatsGuardedEagleEyeTargetAsExposed),
		new("bard offensive target policy preserves eagle eye mitigation", BardOffensiveTargetPolicyPreservesEagleEyeMitigation),
		new("bard offensive target policy penalizes blast resilience", BardOffensiveTargetPolicyPenalizesBlastResilience),
		new("bard harmonic arrow rejects guarded nonlethal target", BardHarmonicArrowRejectsGuardedNonlethalTarget),
		new("bard harmonic arrow accepts unblocked charge overcap", BardHarmonicArrowAcceptsUnblockedChargeOvercap),
		new("bard harmonic arrow accepts low mp conversion", BardHarmonicArrowAcceptsLowMpConversion),
		new("bard pitch perfect accepts repertoire ally focus follow up", BardPitchPerfectAcceptsRepertoireAllyFocusFollowUp),
		new("bard pitch perfect accepts repertoire low mp target", BardPitchPerfectAcceptsRepertoireLowMpTarget),
		new("bard pitch perfect accepts repertoire objective target", BardPitchPerfectAcceptsRepertoireObjectiveTarget),
		new("bard pitch perfect accepts repertoire ally burst", BardPitchPerfectAcceptsRepertoireAllyBurst),
		new("bard pitch perfect rejects repertoire filler", BardPitchPerfectRejectsRepertoireFiller),
		new("bard apex arrow accepts objective line value", BardApexArrowAcceptsObjectiveLineValue),
		new("bard apex arrow accepts guarded objective pressure", BardApexArrowAcceptsGuardedObjectivePressure),
		new("bard apex arrow accepts guarded forced timing", BardApexArrowAcceptsGuardedForcedTiming),
		new("bard apex arrow accepts standalone objective value", BardApexArrowAcceptsStandaloneObjectiveValue),
		new("bard apex arrow accepts standalone ally burst value", BardApexArrowAcceptsStandaloneAllyBurstValue),
		new("bard apex arrow rejects guarded filler", BardApexArrowRejectsGuardedFiller),
		new("bard blast arrow accepts objective displacement", BardBlastArrowAcceptsObjectiveDisplacement),
		new("bard blast arrow rejects resilience displacement", BardBlastArrowRejectsResilienceDisplacement),
		new("bard blast arrow rejects blast ready filler", BardBlastArrowRejectsBlastReadyFiller),
		new("bard encore of light accepts low mp conversion", BardEncoreOfLightAcceptsLowMpConversion),
		new("bard encore of light accepts ally burst window", BardEncoreOfLightAcceptsAllyBurstWindow),
		new("bard encore of light accepts final fantasia push window", BardEncoreOfLightAcceptsFinalFantasiaPushWindow),
		new("bard encore of light rejects blocked filler", BardEncoreOfLightRejectsBlockedFiller),
		new("bard encore of light rejects guard reaction conversion", BardEncoreOfLightRejectsGuardReactionConversion),
		new("bard encore of light rejects unknown guard reaction conversion", BardEncoreOfLightRejectsUnknownGuardReactionConversion),
		new("bard powerful shot accepts safe pressure filler", BardPowerfulShotAcceptsSafePressureFiller),
		new("bard powerful shot accepts neutral safe filler", BardPowerfulShotAcceptsNeutralSafeFiller),
		new("bard powerful shot rejects blocked target", BardPowerfulShotRejectsBlockedTarget),
		new("bard offensive decision policy reruns live guard state", BardOffensiveDecisionPolicyRerunsLiveGuardState),
		new("bard target refresh updates live spatial signals", BardTargetRefreshUpdatesLiveSpatialSignals),
		new("pvp lb json contains verified entries", PvpLbJsonContainsVerifiedEntries),
		new("pvp mitigation json contains resilience", PvpMitigationJsonContainsResilience),
		new("pvp mitigation json contains ranked cc defensive coverage", PvpMitigationJsonContainsRankedCcDefensiveCoverage),
		new("effective hp ignoring guard keeps damage reduction", EffectiveHpIgnoringGuardKeepsDamageReduction),
		new("effective hp ignoring guard keeps non guard invulnerability", EffectiveHpIgnoringGuardKeepsNonGuardInvulnerability),
		new("live target facts use caller health provider", LiveTargetFactsUseCallerHealthProvider),
		new("live target facts use caller status delegate", LiveTargetFactsUseCallerStatusDelegate),
		new("live target facts use caller distance provider", LiveTargetFactsUseCallerDistanceProvider),
		new("live target facts expose ally focus count", LiveTargetFactsExposeAllyFocusCount),
		new("live combatant snapshot uses caller health provider", LiveCombatantSnapshotUsesCallerHealthProvider),
		new("live combatant snapshots skip nulls and use caller health provider", LiveCombatantSnapshotsSkipNullsAndUseCallerHealthProvider),
		new("live combatant snapshots exclude local player", LiveCombatantSnapshotsExcludeLocalPlayer),
		new("frontline role action policy rejects crystalline conflict", FrontlineRoleActionPolicyRejectsCrystallineConflict),
		new("frontline role action policy allows frontline", FrontlineRoleActionPolicyAllowsFrontline),
		new("pvp mode classifier detects crystalline conflict", PvPModeClassifierDetectsCrystallineConflict),
		new("pvp mode classifier detects frontline duties", PvPModeClassifierDetectsFrontlineDuties),
		new("pvp mode classifier rejects crystalline conflict as frontline", PvPModeClassifierRejectsCrystallineConflictAsFrontline),
		new("frontline role action policy keeps action passes separate", FrontlineRoleActionPolicyKeepsActionPassesSeparate),
		new("frontline role action policy defers bard and machinist eagle eye shot", FrontlineRoleActionPolicyDefersBardAndMachinistEagleEyeShot),
		new("frontline eagle eye shot rejects crystalline conflict", FrontlineEagleEyeShotRejectsCrystallineConflict),
		new("bard frontline eagle eye shot waits for controller window", BardFrontlineEagleEyeShotWaitsForControllerWindow),
		new("bard frontline eagle eye shot accepts controlled target", BardFrontlineEagleEyeShotAcceptsControlledTarget),
		new("machinist frontline eagle eye shot rejects healthy filler", MachinistFrontlineEagleEyeShotRejectsHealthyFiller),
		new("machinist frontline eagle eye shot accepts injured target", MachinistFrontlineEagleEyeShotAcceptsInjuredTarget),
		new("machinist frontline eagle eye shot accepts burst setup target", MachinistFrontlineEagleEyeShotAcceptsBurstSetupTarget),
		new("machinist frontline eagle eye shot accepts wildfire target", MachinistFrontlineEagleEyeShotAcceptsWildfireTarget),
		new("machinist frontline eagle eye shot accepts guard pressure target", MachinistFrontlineEagleEyeShotAcceptsGuardPressureTarget),
		new("machinist frontline eagle eye shot secures through guard", MachinistFrontlineEagleEyeShotSecuresThroughGuard),
		new("pvp target ranking filters negative infinity scores", PvPTargetRankingFiltersNegativeInfinityScores),
		new("pvp target ranking orders by supplied comparison", PvPTargetRankingOrdersBySuppliedComparison),
		new("pvp target ranking delegates tiebreaks to comparison", PvPTargetRankingDelegatesTiebreaksToComparison),
		new("pvp target ranking select best returns first ranked or null", PvPTargetRankingSelectBestReturnsFirstRankedOrNull),
	];
}
