namespace RotationSolver.Tests;

internal static partial class PvETestSuite
{
	internal static IReadOnlyList<TestCase> Tests { get; } =
	[
		new("bard ascended dot thresholds honor target time", BardAscendedDotThresholdsHonorTargetTime),
		new("bard ascended dot thresholds use boss fallback only when ttk is unknown", BardAscendedDotThresholdsUseBossFallbackOnlyWhenTtkIsUnknown),
		new("bard ascended dot runtime uses resolved target ttk", BardAscendedDotRuntimeUsesResolvedTargetTtk),
		new("bard ascended song presets map to expected durations", BardAscendedSongPresetsMapToExpectedDurations),
		new("bard ascended radiant finale uses damage buff status", BardAscendedRadiantFinaleUsesDamageBuffStatus),
		new("bard ascended apex spends during burst and mage ballad windows", BardAscendedApexSpendsDuringBurstAndMageBalladWindows),
		new("bard ascended apex holds during army paeon", BardAscendedApexHoldsDuringArmyPaeon),
		new("bard ascended apex cap fallback stays in mage ballad", BardAscendedApexCapFallbackStaysInMageBallad),
		new("bard ascended runtime keeps burst actionability at buff gates", BardAscendedRuntimeKeepsBurstActionabilityAtBuffGates),
		new("bard ascended apex uses planned kill time over song fallback", BardAscendedApexUsesPlannedKillTimeOverSongFallback),
		new("bard ascended blast arrow waits for urgent gcds", BardAscendedBlastArrowWaitsForUrgentGcds),
		new("bard ascended filler waits for enhanced filler or resonant ready", BardAscendedFillerWaitsForEnhancedFillerOrResonantReady),
		new("bard ascended runtime falls back when enhanced filler cannot resolve", BardAscendedRuntimeFallsBackWhenEnhancedFillerCannotResolve),
		new("bard ascended aoe thresholds distinguish gcd and ogcd", BardAscendedAoeThresholdsDistinguishGcdAndOgcd),
		new("bard ascended fresh dots yield to resolved normal aoe", BardAscendedFreshDotsYieldToResolvedNormalAoe),
		new("bard ascended runtime uses resolved aoe target counts", BardAscendedRuntimeUsesResolvedAoeTargetCounts),
		new("bard ascended runtime uses aoe apex and blast before fresh dots", BardAscendedRuntimeUsesAoeApexAndBlastBeforeFreshDots),
		new("bard ascended bloodletter recovery forecasts post spend charges", BardAscendedBloodletterRecoveryForecastsPostSpendCharges),
		new("bard ascended first cycle starts on combat entry and timer reset", BardAscendedFirstCycleStartsOnCombatEntryAndTimerReset),
		new("bard ascended dirty start recovery only uses dungeon song starts", BardAscendedDirtyStartRecoveryOnlyUsesDungeonSongStarts),
		new("bard ascended runtime uses support action hooks", BardAscendedRuntimeUsesSupportActionHooks),
		new("bard ascended runtime recovers dirty song starts before priority", BardAscendedRuntimeRecoversDirtySongStartsBeforePriority),
		new("bard ascended runtime does not cache level synced choices", BardAscendedRuntimeDoesNotCacheLevelSyncedChoices),
		new("bard ascended potion config is constructor safe", BardAscendedPotionConfigIsConstructorSafe),
		new("bard ascended defaults favor guide timings", BardAscendedDefaultsFavorGuideTimings),
		new("bard ascended runtime spends resonant ready before filler", BardAscendedRuntimeSpendsResonantReadyBeforeFiller),
		new("bard ascended runtime spends pitch perfect before burst hold", BardAscendedRuntimeSpendsPitchPerfectBeforeBurstHold),
		new("bard ascended custom timing follows standard burst path", BardAscendedCustomTimingFollowsStandardBurstPath),
		new("bard ascended battle voice waits only for available radiant finale", BardAscendedBattleVoiceWaitsOnlyForAvailableRadiantFinale),
		new("bard ascended potion presets map to expected timings", BardAscendedPotionPresetsMapToExpectedTimings),
		new("bard ascended custom potion timings reject empty input", BardAscendedCustomPotionTimingsRejectEmptyInput),
		new("bard ascended strict standard opener emits scripted requests", BardAscendedStrictStandardOpenerEmitsScriptedRequests),
		new("bard ascended strict adjusted opener emits scripted requests", BardAscendedStrictAdjustedOpenerEmitsScriptedRequests),
		new("bard ascended strict 3 6 9 opener emits scripted requests", BardAscendedStrict369OpenerEmitsScriptedRequests),
		new("bard ascended strict opener preserves pitch perfect safety", BardAscendedStrictOpenerPreservesPitchPerfectSafety),
		new("bard ascended strict opener completes and breaks explicitly", BardAscendedStrictOpenerCompletesAndBreaksExplicitly),
		new("bard ascended strict opener delays adjusted prepull heartbreak until pull", BardAscendedStrictOpenerDelaysAdjustedPrepullHeartbreakUntilPull),
		new("bard ascended strict opener holds pull gcd until adjusted prepull heartbreak ready", BardAscendedStrictOpenerHoldsPullGcdUntilAdjustedPrepullHeartbreakReady),
		new("bard ascended runtime enters strict opener before priority gcds", BardAscendedRuntimeEntersStrictOpenerBeforePriorityGcds),
		new("bard ascended runtime enters strict opener during countdown", BardAscendedRuntimeEntersStrictOpenerDuringCountdown),
		new("bard ascended runtime enters strict opener before priority abilities", BardAscendedRuntimeEntersStrictOpenerBeforePriorityAbilities),
		new("bard ascended bloodletter uses liberal spending with burst reservation", BardAscendedBloodletterUsesLiberalSpendingWithBurstReservation),
		new("bard ascended runtime advances strict opener only after action success", BardAscendedRuntimeAdvancesStrictOpenerOnlyAfterActionSuccess),
		new("ttk estimator matches constant kill rate", TimeToKillEstimatorMatchesConstantKillRate),
		new("ttk estimator tracks steep recent rate below dying threshold", TimeToKillEstimatorTracksSteepRecentRateBelowDyingThreshold),
		new("ttk estimator ignores samples outside window", TimeToKillEstimatorIgnoresSamplesOutsideWindow),
		new("ttk estimator returns nan for too few samples", TimeToKillEstimatorReturnsNaNForTooFewSamples),
		new("ttk estimator returns nan for short span", TimeToKillEstimatorReturnsNaNForShortSpan),
		new("ttk estimator returns nan for flat hp", TimeToKillEstimatorReturnsNaNForFlatHp),
		new("ttk estimator returns nan for rising hp", TimeToKillEstimatorReturnsNaNForRisingHp),
		new("ttk estimator high hp yields large estimate for opener", TimeToKillEstimatorHighHpYieldsLargeEstimateForOpener),
		new("ttk estimator returns nan for nan current hp", TimeToKillEstimatorReturnsNaNForNaNCurrentHp),
		new("scripted opener terminal state always completes", ScriptedOpenerTerminalStateAlwaysCompletes),
		new("scripted opener unusable action breaks", ScriptedOpenerUnusableActionBreaks),
		new("scripted opener gcd breaks while weave pending", ScriptedOpenerGcdBreaksWhileWeavePending),
		new("scripted opener gcd completes past last index and on absent action", ScriptedOpenerGcdCompletesPastLastIndexAndOnAbsentAction),
		new("scripted opener gcd advance opens weave window", ScriptedOpenerGcdAdvanceOpensWeaveWindow),
		new("scripted opener gcd advance without weave jumps step", ScriptedOpenerGcdAdvanceWithoutWeaveJumpsStep),
		new("scripted opener ability without pending slot returns no action", ScriptedOpenerAbilityWithoutPendingSlotReturnsNoAction),
		new("scripted opener ability walks early then late then clears", ScriptedOpenerAbilityWalksEarlyThenLateThenClears),
		new("scripted opener interjection substitutes without advancing", ScriptedOpenerInterjectionSubstitutesWithoutAdvancing),
		new("scripted opener interjection runs when scripted action absent", ScriptedOpenerInterjectionRunsWhenScriptedActionAbsent),
		new("scripted opener suppressed scripted ability skips with advanced state", ScriptedOpenerSuppressedScriptedAbilitySkipsWithAdvancedState),
		new("scripted opener prepull readiness uses script window", ScriptedOpenerPrepullReadinessUsesScriptWindow),
	];
}
